apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: housing-notes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: housing-notes.example.com
      http:
        paths:
          - path: /notes
            pathType: Prefix
            backend:
              service:
                name: housing-notes-backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: housing-notes-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: housing-notes-frontend
                port:
                  number: 80
